TBfighters/tbfightersdotorg

index.html, style.css
Use new name style.css?q=1 to ensure new version is used instead of cached style.css
=> Use background-size: cover for .container

index.html, october-3.html, privacy.html, september-19.html, style.css
swapped hashtag and some CTA language; a few formatting fixes
=> xdrnext update

index.html
Changes grammar from "Take with us action now." to "Take action with us now."
=> fix: fixes some grammar on embeds

index.html
=> feat: p4a cta

index.html, style.css
Notes:
1. To have the print button on ios, you have to open a popup because there is a bug preventing printing correctly in a iframe :(. This is the best way I could fix this.
2. The print functions will be pulled out into their own functions for the coming templates/doc movement
=> feat: cta for lighting up buildings red for world tb day

about.html
Updated links on About Us page: MSF link changed to MSF Access landing page, Div ID #video added so that the link down to John's video would work
=> About links update

action.html
=> Action Grid Re-Ordering

action.html, newsletter.html, style.css
mostly in actions, see https://oreo.is-a.dev/tbfightersdotorg/action (the posts and graphics) I also increased the spacing in the newsletter by 1 br, tell me if it needs more! https://oreo.is-a.dev/tbfightersdotorg/newsletter
=> feat: restyles the graphics section, posts, and adds more spacing to the newsletter page

CONTRIBUTING.md, README.md
docs: remove the "run node" because its not necessary
docs: adding a new page
=> docs: adds docs about contributing and automations

templates/letter-guide.html
Updates the current price of stamps
=> Updates Stamp Price

.github/pull_request_template.md, README.md
Minor Documentation updates and inclusion of PR template!
You can see what this will look like once this is added below!
=> Update GitHub docs

action-page.js, action.html
Removes Light Up CTA from Actions Page & cleans up the JS
=> removes light up CTA

about.html, action.html, activism-guide.html, danaher-rif.html, index.html, johnson-secondary-patents.html, newsletter.html, privacy.html, resources.html, templates/letter-guide.html, timeline.html, update-action/footer.html, update-action/header.html, update-action/index.js, update-action/metadata.html
Makes stuff indented correctly
=> fix: make tab formatting correct in the auto update stuff

about.html, action.html, index.html, timeline.html, update-action/featured-action.html
Swapping tblinks to direct links to the site, when possible it is better to do this so people get to the petition faster! 
Not sure why the automated action added white-space changes 🤷
=> Replace tblink

action.html, index.html, update-action/featured-action.html
Current fax number isn't working, so changing to one of Cepheid's
=> Change fax number in featured action

action.html, index.html, newsletter.html
This also disables when there isn't js because then the bots could just disable js
=> feat: disable form when js is disabled and if the name == email

action.html
The activism guide blurb was removed, this adds it back in.
~~Prev: https://oreo.is-a.dev/tbfightersdotorg/action.html~~
=> feat: re adds the activism guide blurb

action.html
Moved the social media accounts at the top of the action page to their own paragraph, messed with the copy a bit, and added a link to the newsletter as another source of information and updates.
I also moved the socials icons in the middle of the action page to right above the newsletter, since I think it makes more sense to avoid breaking the flow of resources related to directly engaging with action and that the newsletter and socials are more related than the stuff around it previously.
Please don't merge this immediately! I'd like to offer some time for discussion in web dev, especially around the copy changes.
=> Change how TBFighters socials are formatted and add a link to the newsletter

about.html, johnson-secondary-patents.html, newsletter.html, privacy.html, resources.html, style.css, timeline.html
=> feat: add loading button for youtube video embeds and adds target="_blank" to all external links that didn't have it

action.html, activism-guide.html, danaher-rif.html, index.html, resources.html, timeline.html, update-action/featured-action.html
Removes the featured action for now and makes it look good without it.
https://oreo.is-a.dev/tbfightersdotorg/
=> feat: remove featured action for now

action.html, audit.html, index.html, templates/end-tb-now-act.html, templates/letter-guide.html
=> Fix duplicated social media templates and audit page preview

activism-guide.html
Changes to activism guide based on conversation in #writing-and-editing thread 
#Type of Change
- [] replaced “unity” with “teamwork” in section title and paragraph text
- [] deleted “-avoid acting independently”
=> Update activism-guide copy

hill-day.html
some fixes discussed in discord
=> Hill day update

action.html, index.html, update-action/featured-action.html
Update the featured action to point towards the Hill Day templates and action
=> Update featured action

hill-day/archive.html
=> Update last week's training session with links to recording and templates

hill-day/archive.html, templates/hill-day.html
Fix some small mistakes on the Hill Day templates and add more info to the blurb for the March meeting.
=> Hill Day updates and fixes

action.html, hill-day/index.html, index.html, templates/usaid-freeze.html, update-action/featured-action.html, usaid-freeze.html
=> feat: update featured action and link to different template page

hill-day/archive.html
=> Add edited versions of rexording and slides to Hill Day trainings archive

hill-day/index.html
Removed link to hill day signups
=> close hill day signups

book-club/index.html
=> feat: add eitb doc link

book-club/index.html
Replace discord invite link with redirect
=> Update discord invite link

resources.html
Update PIH link to https://act.pih.org/tb
=> update pih link

action-page.js
=> grammar check

action.html, index.html, templates/dear-colleague.html, templates/hill-day.html, update-action/featured-action.html
https://tbfighters.a-good.dev/templates/dear-colleague
=> feat: dear colleage templates

book-club/index.html, book-club/qna.html
=> feat: add livestream embed

404.html
=> create 404 page

action.html, index.html, update-action/featured-action.html
=> feat: update featured action

book-club/qna.html
=> feat: add qna link

book-club/book-club.css, book-club/index.html, book-club/qna.html
=> feat: update book club page for MBM

action.html, index.html, update-action/featured-action.html
Added new featured action per request from team in Comms chat after PIH's asks in Joia chat yesterday
- [X ] Updated content (New CTA, updated wording, etc.)
=> Update Featured Action PEPFAR CTA from Joia call
